wandb_version: 1

bot_version:
  desc: null
  value: 1.0.0
model:
  desc: null
  value: gpt-3.5-turbo-16k
_wandb:
  desc: null
  value:
    python_version: 3.13.3
    cli_version: 0.16.3
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1745328587.15342
    t:
      1:
      - 55
      - 95
      2:
      - 55
      - 95
      3:
      - 16
      - 23
      4: 3.13.3
      5: 0.16.3
      8:
      - 5
      13: linux-x86_64
