_wandb:
    value:
        cli_version: 0.19.9
        m: []
        python_version: 3.13.3
        t:
            "1":
                - 55
                - 95
                - 105
            "2":
                - 55
                - 95
                - 105
            "3":
                - 16
                - 23
                - 55
            "4": 3.13.3
            "5": 0.19.9
            "8":
                - 5
            "12": 0.19.9
            "13": linux-x86_64
bot_version:
    value: 1.0.1
model:
    value: gpt-3.5-turbo-16k
